### ISSUE TITLE
Mac 上需要  修改一行代码

### ISSUE THREAD

**Issue by binyoucai** [Python3WebSpider/DeepLearningSlideCaptcha#1]
detect.py
改53行代码
model.load_state_dict(torch.load(opt.weights_path, map_location="cuda" if torch.cuda.is_available() else "cpu"))

因为加载时候默认用的GPU

**Comment by Germey** [comment]
多谢建议，我修改一下

**Comment by misstt123** [comment]
训练大概需要多长时间，如果是1060的话

**Comment by Germey** [comment]
不到半小时应该能比较好吧，我用 P100 的话其实几分钟就行
