### ISSUE TITLE
请问 崔大 checkpoints/yolov3_ckpt_pretrain.pth 该文件下载下来只有100多k

### ISSUE THREAD

**Issue by Iceprism** [Python3WebSpider/DeepLearningSlideCaptcha#4]

**Comment by Germey** [comment]
这里我的 Git LFS 流量超了，无法下载了，可以手动下载模型放到 checkpoints 文件夹。网盘：链接:https://pan.baidu.com/s/1_do6DDEzViYFq_JASSl5Bg  密码:5bni
