### ISSUE TITLE
yolov3_ckpt_pretrain.pth不能正常下载吗

### ISSUE THREAD

**Issue by zhangdashan123** [Python3WebSpider/DeepLearningSlideCaptcha#5]
我这边一直下载失败.几kb

**Comment by Germey** [comment]
这里我的 Git LFS 流量超了，无法下载了，可以手动下载模型放到 checkpoints 文件夹。网盘：链接:https://pan.baidu.com/s/1_do6DDEzViYFq_JASSl5Bg  密码:5bni

**Comment by zhangdashan123** [comment]
感谢
